### ISSUE TITLE
Info_ap

### ISSUE THREAD

**Issue by Ant4r3z** [ronaldo26rodrigues/Projeto1-AOC#8]
![image](https://user-images.githubusercontent.com/70300685/223291894-e7ea2819-cb49-441d-92a9-0212ca7cd91e.png)
![image](https://user-images.githubusercontent.com/70300685/223292304-6c84ee42-ff1d-4ca9-868e-2767e90d92d8.png)

Ao final da função info_ap, ele entra no "comando inválido"

_Originally posted by @Ant4r3z in https://github.com/ronaldo26rodrigues/Projeto1-AOC/pull/5#pullrequestreview-1327467491_

**Comment by ronaldo26rodrigues** [comment]
Era uma letrinha faltando. Nos comandos de mensagem ao invés de manipular $sp estava manipulando $s0. Não quebrou o programa mas deixou ele confuso :P
